services:
  app:
    image: python:3.11-slim-buster
    ports:
      - 0.0.0.0:8000:8000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: my_database

  mysql:
    image: mysql:8.0
    volumes:
      - django-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: my_database

volumes:
  todo-mysql-data: {}