version: '3'
services:
  postgres:
    image: postgres:latest
    networks:
      - jenkins_default
    volumes:
      - django-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: my_database

  app:
    build:
      context: /var/jenkins_home/workspace/backend_/  # Ruta especifica del contexto o #context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - jenkins_default
    volumes:
      - .:/app
      - backend__jenkins_jenkins_home:/var/jenkins_home  # Nuevo volumen agregado
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: my_database
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@gmail.com
      DJANGO_SUPERUSER_PASSWORD: admin369
    command: bash -c python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser --no-input && python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    stdin_open: true  # Mantén STDIN abierto para que el contenedor no se cierre automáticamente #command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    tty: true         # Mantén TTY abierto para que el contenedor no se cierre automáticamente

volumes:
  django-postgres-data: {}
  backend__jenkins_jenkins_home: {}  # Nuevo volumen agregado

networks:
  jenkins_default:
    external: true

#networks:
#  mynetwork: {}
